version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecopantry
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-ep
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend-ep:/app          
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ecopantry
    depends_on:
      - postgres

volumes:
  postgres-data:
